version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker Image
          command: |
            docker build -t vrushankpatel5/complexica-server:latest .
      - run:
          name: Push Docker Image
          command: |
            docker push vrushankpatel5/complexica-server:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push