version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker Image
          command: |
            docker build -t vrushankpatel5/complexica-server:1.0 .
      - run:
          name: Push Docker Image
          command: |
            docker push vrushankpatel5/complexica-server:1.0

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push
